github.com:
    user: TaylorJonesTRT
    oauth_token: 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
    git_protocol: ssh
    users:
        TaylorJonesTRT:
            oauth_token: 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
